resolvers += "Flyway" at "https://flywaydb.org/repo"

addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.8.0")
addSbtPlugin("org.flywaydb"      % "flyway-sbt"          % "4.0.3")
addSbtPlugin("com.geirsson"      %% "sbt-scalafmt"       % "0.5.4")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.5.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"         % "1.0.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.1.4")
addSbtPlugin("io.get-coursier"   % "sbt-coursier"        % "1.0.0-M15-1")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.6.1")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.4.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "0.8.5")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.3.0")
addSbtPlugin("org.wartremover"   % "sbt-wartremover"     % "1.3.0")
addSbtPlugin("com.orrsella"      % "sbt-stats"           % "1.0.5")
